repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^scripts/
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^scripts/
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: forbid-tabs
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [
         "flake8-bugbear",
         "flake8-comprehensions",
         "flake8-mutable",
         "flake8-print",
         "flake8-simplify",
         "dlint",
     ]
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
    - id: bandit
      args: ['-iii', '-ll']
-   repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.3
    hooks:
    -   id: pycln
