version: '3.9'

services:
  web:
    build: .
    env_file:
      - ./reunion/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12.2
    env_file:
      - ./database.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure

volumes:
  postgres_data:
