# Generated by Django 4.1.1 on 2022-10-02 05:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0002_post_like_follow_comment_follow_unique_followers"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_followers",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_datetime", None)),
                fields=("user_id", "follower"),
                name="unique_followers",
            ),
        ),
    ]
