# Generated by Django 4.1.1 on 2022-10-02 08:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0003_remove_follow_unique_followers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="description",
        ),
    ]
