# Generated by Django 4.1.1 on 2022-10-02 16:30
from django.db import migrations
from django.db import models

import social_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("social_app", "0004_rename_body_post_description"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", social_app.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
